name: 'ReleaseCheck'
description: 'A command line tool that fetches released iOS and tvOS apps from the iTunes Search API and publishes in a Slack channel'
branding:
  icon: 'bell'
  color: 'blue'

inputs:
  apple-id:
    description: 'Apple ID of the app'
    required: true
  platforms:
    description: 'Platforms to be checked, iOS and tvOS are supported'
    required: true
  slack-channel:
    description: 'Name of the Slack channel to post the release'
    required: true
  slack-bot-token:
    description: 'Token of the Slack bot that will be used to post'
    required: true
  verbose:
    description: 'If true it logs more information, deafult is false'
    required: false
    default: false

runs:
  using: 'composite'
  steps:
    - name: 'Checkout Swift Package'
      uses: actions/checkout@v4
      with:
        path: recheck
        repository: 'diogot/ReleaseCheck'
        fetch-depth: 2
    - name: 'Check Versions'
      run: cd recheck && swift run recheck -a ${{ inputs.apple-id }} -p ${{ inputs.platforms }} -t ${{ inputs.slack-bot-token }} -c ${{ inputs.slack-channel }} ${{ inputs.verbose == true && '-v' || ' ' }}
      shell: bash
